project:
  type: website
  output-dir: docs
  title: "ADHD in Adults"

website:
  title: "ADHD in Adults"
  navbar:
    left:
      - href: index.qmd
        text: ADHD in Adults

execute:
  echo: false
  warning: false
  message: false
  cache: false
  freeze: auto
